# https://taskfile.dev

version: "3"

vars:
  rockspec: ./nvim-kitty-dev-2.rockspec

env:
  LUAROCKS_PREFIX: "{{.ROOT_DIR}}/lua_modules"
  LUA_PATH: "$LUAROCKS_PREFIX/share/lua/5.1/?.lua;$LUAROCKS_PREFIX/share/lua/5.1/?/init.lua;$LUA_PATH"
  LUA_CPATH: "$LUAROCKS_PREFIX/lib/lua/5.1/?.so;$LUA_CPATH"
  LUAROCKS_CONFIG: "{{.ROOT_DIR}}/config.lua"
  PATH: "$LUAROCKS_PREFIX/bin:$PATH"

tasks:
  default:
    - task: test

  test:
    silent: true
    sources:
      - "lua/**/*.lua"
      - "tests/**/*.lua"
    cmd: luarocks test {{.CLI_ARGS}}

  nvim:
    interactive: true
    env:
      XDG_CONFIG_HOME: ".tests/xdg/config/"
      XDG_STATE_HOME: ".tests/xdg/local/state/"
      XDG_DATA_HOME: ".tests/xdg/local/share/"

    cmd: nvim -u ./tests/init.lua

  plug.add:
    desc: "Add a plugin to the pack directory, usage: task plug.add [start=URL] [opt=URL]"

    aliases: [pa]
    vars:
      plug_dir: ".tests/xdg/local/share/nvim/site/pack/testing/start"
      start: '{{default .start ""}}'
      opt: '{{default .opt ""}}'

    cmd: |
      start={{shellQuote .start}}
      opt={{shellQuote .opt}}
      kind=""
      url=""

      if [ -n "$start" ]; then
        kind="start"
        url="$start"
      elif [ -n "$opt" ]; then
        kind="opt"
        url="$opt"
      fi

      basename="$(basename "$url")"

      path=".tests/xdg/local/share/nvim/site/pack/testing/$kind/$basename"

      git submodule add --force --depth 1 "$url" "$path"

  add:type:
    vars:
      URL: "https://github.com/LuaCATS/{{.name}}.git"
      PATH: "meta/3rd/{{.name}}"
    cmd: git submodule add --force --depth 1 {{.URL}} {{.PATH}}

  install:
    aliases: [i]
    cmd: luarocks install --force --pin --deps-mode=one --tree=lua_modules --only-deps {{.rockspec}}

  install:test:
    aliases: [it]
    cmd: luarocks --tree=lua_modules test --prepare {{.rockspec}}

  lint:
    cmd: selene .

  lint.luasp:
    silent: true
    vars:
      pager:
        sh: command -v tspin || command -v less
    env:
      VIMRUNTIME:
        sh: nvim --clean --headless --cmd 'echo $VIMRUNTIME|q' 2>&1 1>/dev/null
    cmds:
      - ./.tests/xdg/local/share/nvim/mason/bin/lua-language-server --check .  --logpath=.tmp
      - ./tests/nvim -l ./tests/lualsp-report.lua .tmp/check.json | {{.pager}}
